CREATE TABLE "owner"
(
  "id" bigserial PRIMARY KEY,
  "first_name" VARCHAR(20) NOT NULL,
  "last_name" VARCHAR(20) NOT NULL,
  "country" VARCHAR(20) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT(NOW())
);

CREATE TABLE "car"
(
    "vin" VARCHAR(20) PRIMARY KEY,
    "owner_id" bigint NOT NULL ,
    "make" VARCHAR(20) NOT NULL,
    "model" VARCHAR(30) NOT NULL,
    "year" int NOT NULL
);


CREATE TABLE "maintenance"
(
  "maintenance_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_vin" VARCHAR(20) NOT NULL ,
  "maintenance_type" VARCHAR(30) NOT NULL ,
  "mileage" int NOT NULL ,
  "created_at" timestamptz NOT NULL DEFAULT(NOW())
);


CREATE INDEX ON "car" ("vin");
CREATE INDEX ON "maintenance" ("car_vin");
ALTER TABLE "car" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id");
ALTER TABLE "maintenance" ADD FOREIGN KEY ("car_vin") REFERENCES "car" ("vin")