// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateCar(ctx context.Context, arg CreateCarParams) (Car, error)
	CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCarByVIN(ctx context.Context, vin string) error
	DeleteMaintenanceByID(ctx context.Context, maintenanceID int32) error
	DeleteMaintenanceByVIN(ctx context.Context, carVin string) error
	DeleteUserByUsername(ctx context.Context, username string) error
	GetCarByVIN(ctx context.Context, vin string) (Car, error)
	GetListMaintenancesByVIN(ctx context.Context, arg GetListMaintenancesByVINParams) ([]Maintenance, error)
	GetMaintenanceByID(ctx context.Context, maintenanceID int32) (Maintenance, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCarsByUsername(ctx context.Context, arg ListCarsByUsernameParams) ([]Car, error)
	UpdateCarMakeByVIN(ctx context.Context, arg UpdateCarMakeByVINParams) (Car, error)
	UpdateCarModelByVIN(ctx context.Context, arg UpdateCarModelByVINParams) (Car, error)
	UpdateCarUsernameByVIN(ctx context.Context, arg UpdateCarUsernameByVINParams) (Car, error)
	UpdateCarYearByVIN(ctx context.Context, arg UpdateCarYearByVINParams) (Car, error)
}

var _ Querier = (*Queries)(nil)
