name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: auto_care
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
            


    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - uses: actions/checkout@v3

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
