// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/IvanRoussev/autocare/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/IvanRoussev/autocare/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateCar mocks base method.
func (m *MockStore) CreateCar(arg0 context.Context, arg1 db.CreateCarParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCar", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCar indicates an expected call of CreateCar.
func (mr *MockStoreMockRecorder) CreateCar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCar", reflect.TypeOf((*MockStore)(nil).CreateCar), arg0, arg1)
}

// CreateMaintenance mocks base method.
func (m *MockStore) CreateMaintenance(arg0 context.Context, arg1 db.CreateMaintenanceParams) (db.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMaintenance", arg0, arg1)
	ret0, _ := ret[0].(db.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMaintenance indicates an expected call of CreateMaintenance.
func (mr *MockStoreMockRecorder) CreateMaintenance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaintenance", reflect.TypeOf((*MockStore)(nil).CreateMaintenance), arg0, arg1)
}

// CreateOwner mocks base method.
func (m *MockStore) CreateOwner(arg0 context.Context, arg1 db.CreateOwnerParams) (db.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOwner", arg0, arg1)
	ret0, _ := ret[0].(db.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOwner indicates an expected call of CreateOwner.
func (mr *MockStoreMockRecorder) CreateOwner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOwner", reflect.TypeOf((*MockStore)(nil).CreateOwner), arg0, arg1)
}

// DeleteCarByVIN mocks base method.
func (m *MockStore) DeleteCarByVIN(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCarByVIN", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCarByVIN indicates an expected call of DeleteCarByVIN.
func (mr *MockStoreMockRecorder) DeleteCarByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCarByVIN", reflect.TypeOf((*MockStore)(nil).DeleteCarByVIN), arg0, arg1)
}

// DeleteMaintenanceByID mocks base method.
func (m *MockStore) DeleteMaintenanceByID(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaintenanceByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaintenanceByID indicates an expected call of DeleteMaintenanceByID.
func (mr *MockStoreMockRecorder) DeleteMaintenanceByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaintenanceByID", reflect.TypeOf((*MockStore)(nil).DeleteMaintenanceByID), arg0, arg1)
}

// DeleteMaintenanceByVIN mocks base method.
func (m *MockStore) DeleteMaintenanceByVIN(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaintenanceByVIN", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaintenanceByVIN indicates an expected call of DeleteMaintenanceByVIN.
func (mr *MockStoreMockRecorder) DeleteMaintenanceByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaintenanceByVIN", reflect.TypeOf((*MockStore)(nil).DeleteMaintenanceByVIN), arg0, arg1)
}

// DeleteOwnerByID mocks base method.
func (m *MockStore) DeleteOwnerByID(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOwnerByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOwnerByID indicates an expected call of DeleteOwnerByID.
func (mr *MockStoreMockRecorder) DeleteOwnerByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOwnerByID", reflect.TypeOf((*MockStore)(nil).DeleteOwnerByID), arg0, arg1)
}

// GetCarByVIN mocks base method.
func (m *MockStore) GetCarByVIN(arg0 context.Context, arg1 string) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarByVIN indicates an expected call of GetCarByVIN.
func (mr *MockStoreMockRecorder) GetCarByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarByVIN", reflect.TypeOf((*MockStore)(nil).GetCarByVIN), arg0, arg1)
}

// GetListMaintenancesByVIN mocks base method.
func (m *MockStore) GetListMaintenancesByVIN(arg0 context.Context, arg1 db.GetListMaintenancesByVINParams) ([]db.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListMaintenancesByVIN", arg0, arg1)
	ret0, _ := ret[0].([]db.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListMaintenancesByVIN indicates an expected call of GetListMaintenancesByVIN.
func (mr *MockStoreMockRecorder) GetListMaintenancesByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListMaintenancesByVIN", reflect.TypeOf((*MockStore)(nil).GetListMaintenancesByVIN), arg0, arg1)
}

// GetMaintenanceByID mocks base method.
func (m *MockStore) GetMaintenanceByID(arg0 context.Context, arg1 int32) (db.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintenanceByID", arg0, arg1)
	ret0, _ := ret[0].(db.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaintenanceByID indicates an expected call of GetMaintenanceByID.
func (mr *MockStoreMockRecorder) GetMaintenanceByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintenanceByID", reflect.TypeOf((*MockStore)(nil).GetMaintenanceByID), arg0, arg1)
}

// GetOwnerByID mocks base method.
func (m *MockStore) GetOwnerByID(arg0 context.Context, arg1 int64) (db.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerByID", arg0, arg1)
	ret0, _ := ret[0].(db.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerByID indicates an expected call of GetOwnerByID.
func (mr *MockStoreMockRecorder) GetOwnerByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerByID", reflect.TypeOf((*MockStore)(nil).GetOwnerByID), arg0, arg1)
}

// ListCars mocks base method.
func (m *MockStore) ListCars(arg0 context.Context, arg1 db.ListCarsParams) ([]db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCars", arg0, arg1)
	ret0, _ := ret[0].([]db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCars indicates an expected call of ListCars.
func (mr *MockStoreMockRecorder) ListCars(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCars", reflect.TypeOf((*MockStore)(nil).ListCars), arg0, arg1)
}

// ListCarsByOwnerID mocks base method.
func (m *MockStore) ListCarsByOwnerID(arg0 context.Context, arg1 db.ListCarsByOwnerIDParams) ([]db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCarsByOwnerID", arg0, arg1)
	ret0, _ := ret[0].([]db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCarsByOwnerID indicates an expected call of ListCarsByOwnerID.
func (mr *MockStoreMockRecorder) ListCarsByOwnerID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCarsByOwnerID", reflect.TypeOf((*MockStore)(nil).ListCarsByOwnerID), arg0, arg1)
}

// ListMaintenances mocks base method.
func (m *MockStore) ListMaintenances(arg0 context.Context, arg1 db.ListMaintenancesParams) ([]db.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaintenances", arg0, arg1)
	ret0, _ := ret[0].([]db.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaintenances indicates an expected call of ListMaintenances.
func (mr *MockStoreMockRecorder) ListMaintenances(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaintenances", reflect.TypeOf((*MockStore)(nil).ListMaintenances), arg0, arg1)
}

// ListOwners mocks base method.
func (m *MockStore) ListOwners(arg0 context.Context, arg1 db.ListOwnersParams) ([]db.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwners", arg0, arg1)
	ret0, _ := ret[0].([]db.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwners indicates an expected call of ListOwners.
func (mr *MockStoreMockRecorder) ListOwners(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwners", reflect.TypeOf((*MockStore)(nil).ListOwners), arg0, arg1)
}

// UpdateCarMakeByVIN mocks base method.
func (m *MockStore) UpdateCarMakeByVIN(arg0 context.Context, arg1 db.UpdateCarMakeByVINParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarMakeByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCarMakeByVIN indicates an expected call of UpdateCarMakeByVIN.
func (mr *MockStoreMockRecorder) UpdateCarMakeByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarMakeByVIN", reflect.TypeOf((*MockStore)(nil).UpdateCarMakeByVIN), arg0, arg1)
}

// UpdateCarModelByVIN mocks base method.
func (m *MockStore) UpdateCarModelByVIN(arg0 context.Context, arg1 db.UpdateCarModelByVINParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarModelByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCarModelByVIN indicates an expected call of UpdateCarModelByVIN.
func (mr *MockStoreMockRecorder) UpdateCarModelByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarModelByVIN", reflect.TypeOf((*MockStore)(nil).UpdateCarModelByVIN), arg0, arg1)
}

// UpdateCarOwnerIdByVIN mocks base method.
func (m *MockStore) UpdateCarOwnerIdByVIN(arg0 context.Context, arg1 db.UpdateCarOwnerIdByVINParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarOwnerIdByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCarOwnerIdByVIN indicates an expected call of UpdateCarOwnerIdByVIN.
func (mr *MockStoreMockRecorder) UpdateCarOwnerIdByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarOwnerIdByVIN", reflect.TypeOf((*MockStore)(nil).UpdateCarOwnerIdByVIN), arg0, arg1)
}

// UpdateCarYearByVIN mocks base method.
func (m *MockStore) UpdateCarYearByVIN(arg0 context.Context, arg1 db.UpdateCarYearByVINParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarYearByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCarYearByVIN indicates an expected call of UpdateCarYearByVIN.
func (mr *MockStoreMockRecorder) UpdateCarYearByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarYearByVIN", reflect.TypeOf((*MockStore)(nil).UpdateCarYearByVIN), arg0, arg1)
}

// UpdateMaintenanceMileageByVIN mocks base method.
func (m *MockStore) UpdateMaintenanceMileageByVIN(arg0 context.Context, arg1 db.UpdateMaintenanceMileageByVINParams) (db.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaintenanceMileageByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMaintenanceMileageByVIN indicates an expected call of UpdateMaintenanceMileageByVIN.
func (mr *MockStoreMockRecorder) UpdateMaintenanceMileageByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaintenanceMileageByVIN", reflect.TypeOf((*MockStore)(nil).UpdateMaintenanceMileageByVIN), arg0, arg1)
}

// UpdateMaintenanceTypeByVIN mocks base method.
func (m *MockStore) UpdateMaintenanceTypeByVIN(arg0 context.Context, arg1 db.UpdateMaintenanceTypeByVINParams) (db.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaintenanceTypeByVIN", arg0, arg1)
	ret0, _ := ret[0].(db.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMaintenanceTypeByVIN indicates an expected call of UpdateMaintenanceTypeByVIN.
func (mr *MockStoreMockRecorder) UpdateMaintenanceTypeByVIN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaintenanceTypeByVIN", reflect.TypeOf((*MockStore)(nil).UpdateMaintenanceTypeByVIN), arg0, arg1)
}

// UpdateOwnerCountryByID mocks base method.
func (m *MockStore) UpdateOwnerCountryByID(arg0 context.Context, arg1 db.UpdateOwnerCountryByIDParams) (db.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnerCountryByID", arg0, arg1)
	ret0, _ := ret[0].(db.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOwnerCountryByID indicates an expected call of UpdateOwnerCountryByID.
func (mr *MockStoreMockRecorder) UpdateOwnerCountryByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnerCountryByID", reflect.TypeOf((*MockStore)(nil).UpdateOwnerCountryByID), arg0, arg1)
}

// UpdateOwnerFirstNameByID mocks base method.
func (m *MockStore) UpdateOwnerFirstNameByID(arg0 context.Context, arg1 db.UpdateOwnerFirstNameByIDParams) (db.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnerFirstNameByID", arg0, arg1)
	ret0, _ := ret[0].(db.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOwnerFirstNameByID indicates an expected call of UpdateOwnerFirstNameByID.
func (mr *MockStoreMockRecorder) UpdateOwnerFirstNameByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnerFirstNameByID", reflect.TypeOf((*MockStore)(nil).UpdateOwnerFirstNameByID), arg0, arg1)
}

// UpdateOwnerLastNameByID mocks base method.
func (m *MockStore) UpdateOwnerLastNameByID(arg0 context.Context, arg1 db.UpdateOwnerLastNameByIDParams) (db.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnerLastNameByID", arg0, arg1)
	ret0, _ := ret[0].(db.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOwnerLastNameByID indicates an expected call of UpdateOwnerLastNameByID.
func (mr *MockStoreMockRecorder) UpdateOwnerLastNameByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnerLastNameByID", reflect.TypeOf((*MockStore)(nil).UpdateOwnerLastNameByID), arg0, arg1)
}
